/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import {
  Activity,
  Banknote,
  Coins,
  Database,
  KeyRound,
  Layers,
  RadioTower,
  Sparkles,
  SquareStack,
  Timer,
  TrendingUp,
  type LucideIcon,
} from 'lucide-react'
import { useTranslation } from 'react-i18next'

import { SectionPageLayout } from '@/components/layout'
import { Badge } from '@/components/ui/badge'
import { Label } from '@/components/ui/label'
import { Skeleton } from '@/components/ui/skeleton'
import { Switch } from '@/components/ui/switch'
import { PanelWrapper } from '@/features/dashboard/components/ui/panel-wrapper'
import { StatCard } from '@/features/dashboard/components/ui/stat-card'
import { formatCompactNumber, formatNumber, formatQuota } from '@/lib/format'
import { cn } from '@/lib/utils'

import { DEFAULT_SUMMARY_RANGE } from '../constants'
import { useObservabilitySummary } from '../hooks'
import { buildHourlyActivitySpec, buildTrafficTrendSpec } from '../lib/charts'
import {
  formatLatencyMs,
  formatSuccessRate,
  formatTokenCount,
} from '../lib/format'
import { resolveTimeRange } from '../lib/query'
import type {
  FailureSource,
  HealthTimelinePoint,
  ObservabilitySearch,
  ObservabilitySummary,
  TopChannelRow,
  TopModelRow,
  TopTokenRow,
} from '../types'
import { ChartPanel } from './chart-panel'
import { RangeSelector } from './range-selector'

interface OverviewPageProps {
  search: ObservabilitySearch
  onSearchChange: (patch: Partial<ObservabilitySearch>) => void
}

type Tone = 'accent-1' | 'accent-2' | 'accent-3'

interface MetricDefinition {
  key: string
  titleKey: string
  value: string
  /** i18n key for the sub-line. */
  descriptionKey?: string
  /** Preformatted sub-line (values that are not translation keys). */
  description?: string
  /**
   * i18n key for a second, muted sub-line that qualifies the value itself
   * rather than describing it (currently only the stream-calls denominator).
   */
  noteKey?: string
  icon: LucideIcon
  tone: Tone
}

/**
 * Success Rate sub-line. Scope v2: every counter comes from the consumption
 * logs, so "success / total" is always arithmetically consistent; only the
 * *failure* count switches source, and that has to be disclosed on the card.
 */
function failureSourceNoteKey(
  failureSource: FailureSource
): string | undefined {
  if (failureSource === 'error_log') return 'Failures counted since error logs were enabled'
  if (failureSource === 'perf_metrics') return 'Failures are estimated; enable error logs for exact counts'
  return undefined
}

function buildMetrics(
  summary: ObservabilitySummary,
  failureSource: FailureSource
): MetricDefinition[] {
  return [
    {
      key: 'calls',
      titleKey: 'Total Calls',
      value: formatNumber(summary.total_calls),
      descriptionKey: 'Requests matched in the selected range',
      icon: Activity,
      tone: 'accent-1',
    },
    {
      key: 'tokens',
      titleKey: 'Total Tokens',
      value: formatTokenCount(summary.total_tokens),
      descriptionKey: 'Prompt and completion tokens combined',
      icon: Layers,
      tone: 'accent-2',
    },
    {
      key: 'cost',
      titleKey: 'Total Cost',
      value: formatQuota(summary.total_quota),
      descriptionKey: 'Billed quota for the selected range',
      icon: Banknote,
      tone: 'accent-3',
    },
    {
      key: 'latency',
      titleKey: 'Average Latency',
      value: formatLatencyMs(summary.average_latency_ms),
      descriptionKey: 'End-to-end request duration',
      icon: Timer,
      tone: 'accent-1',
    },
    {
      key: 'success',
      titleKey: 'Success Rate',
      value: formatSuccessRate(summary.success_rate),
      description: `${formatNumber(summary.success_calls)} / ${formatNumber(summary.total_calls)}`,
      noteKey: failureSourceNoteKey(failureSource),
      icon: TrendingUp,
      tone: 'accent-2',
    },
    {
      key: 'prompt-tokens',
      titleKey: 'Prompt Tokens',
      value: formatTokenCount(summary.prompt_tokens),
      descriptionKey: 'Tokens sent to the upstream model',
      icon: SquareStack,
      tone: 'accent-3',
    },
    {
      key: 'completion-tokens',
      titleKey: 'Completion Tokens',
      value: formatTokenCount(summary.completion_tokens),
      descriptionKey: 'Tokens generated by the model',
      icon: Sparkles,
      tone: 'accent-1',
    },
    {
      key: 'cached-tokens',
      titleKey: 'Cached Tokens',
      value: formatTokenCount(summary.cached_tokens),
      descriptionKey: 'Served from the provider prompt cache',
      icon: Database,
      tone: 'accent-2',
    },
    {
      key: 'stream-calls',
      titleKey: 'Stream Calls',
      value: formatNumber(summary.stream_calls),
      descriptionKey: 'Requests served as a stream',
      // 口径 v2：总数与流式数均取自消费日志，混源条件不复存在，故原先的
      // 「From consumption logs」限定语已删除（否则它在错误日志关闭时仍会渲染，
      // 而它描述的「总数来自 perf_metrics」在 v2 下已不成立，属于误导）。
      icon: RadioTower,
      tone: 'accent-3',
    },
    {
      key: 'active-keys',
      titleKey: 'Active API Keys',
      value: formatNumber(summary.unique_tokens),
      descriptionKey: 'Distinct API keys that made a request',
      icon: KeyRound,
      tone: 'accent-1',
    },
  ]
}

interface TopListRow {
  key: string
  label: string
  calls: number
  tokens: number
  quota: number
}

interface TopListProps {
  title: string
  rows: TopListRow[]
  emptyMessage: string
}

function TopList(props: TopListProps) {
  const { t } = useTranslation()
  const maxTokens = Math.max(1, ...props.rows.map((row) => row.tokens))

  return (
    <PanelWrapper
      title={props.title}
      empty={props.rows.length === 0}
      emptyMessage={props.emptyMessage}
      height='h-56'
      contentClassName='p-0'
    >
      <ul className='divide-border/60 divide-y'>
        {props.rows.map((row) => (
          <li key={row.key} className='px-4 py-2.5 sm:px-5'>
            <div className='flex items-center justify-between gap-3'>
              <span className='truncate text-sm font-medium' title={row.label}>
                {row.label}
              </span>
              <span className='shrink-0 text-xs font-semibold tabular-nums'>
                {t('{{tokens}} tokens', {
                  tokens: formatTokenCount(row.tokens),
                })}
              </span>
            </div>
            <div className='text-muted-foreground mt-1 text-xs tabular-nums'>
              {t('{{calls}} calls · {{amount}}', {
                calls: formatNumber(row.calls),
                amount: formatQuota(row.quota),
              })}
            </div>
            <div
              className='bg-muted mt-1.5 h-1 overflow-hidden rounded-full'
              aria-hidden='true'
            >
              <div
                className='bg-chart-1 h-full rounded-full'
                style={{ width: `${(row.tokens / maxTokens) * 100}%` }}
              />
            </div>
          </li>
        ))}
      </ul>
    </PanelWrapper>
  )
}

function toTopModelRows(rows: TopModelRow[]): TopListRow[] {
  return rows.map((row) => ({
    key: row.model_name || '-',
    label: row.model_name || '-',
    calls: row.calls,
    tokens: row.total_tokens,
    quota: row.quota,
  }))
}

function toTopTokenRows(rows: TopTokenRow[]): TopListRow[] {
  return rows.map((row) => ({
    key: String(row.token_id),
    label: row.token_name || String(row.token_id),
    calls: row.calls,
    tokens: row.total_tokens,
    quota: row.quota,
  }))
}

function toTopChannelRows(rows: TopChannelRow[]): TopListRow[] {
  return rows.map((row) => ({
    key: String(row.channel_id),
    label: row.channel_name || String(row.channel_id),
    calls: row.calls,
    tokens: row.total_tokens,
    quota: row.quota,
  }))
}

/** 10-minute buckets as a bar lane, coloured by the bucket's failure ratio. */
/** Bucket colour by failure ratio: healthy, degraded, then failing. */
function healthToneClass(ratio: number): string {
  if (ratio > 0.1) return 'bg-destructive/80'
  if (ratio > 0) return 'bg-warning/80'
  return 'bg-success/70'
}

function HealthTimelinePanel(props: {
  points: HealthTimelinePoint[]
  errorLogEnabled: boolean
  loading: boolean
}) {
  const { t } = useTranslation()
  const maxCalls = Math.max(1, ...props.points.map((point) => point.calls))

  if (props.loading) {
    return (
      <PanelWrapper
        title={t('Request Health')}
        loading
        className='flex flex-col'
        contentClassName='flex flex-1 flex-col'
        // h-full 撑满拉伸后的卡片；min-h-14 兜住单列（移动端）下卡片高度为 auto、
        // h-full 无法求解时骨架塌成 0 的情况。
        height='h-full min-h-14'
      />
    )
  }

  // 与左侧图表（h-64）同行时，grid 的 stretch 会把本卡片拉到同高。className 让卡片
  // 成为纵向 flex 容器（PanelWrapper 只把它拼到卡片外层），contentClassName 让内容区
  // 吃掉表头之外的全部高度，车道再 h-full 铺满——否则车道固定高度只占卡片一小截。
  return (
    <PanelWrapper
      title={t('Request Health')}
      description={t('10-minute buckets · last 24 hours')}
      headerActions={
        props.errorLogEnabled ? undefined : (
          <Badge variant='secondary' className='text-muted-foreground text-xs'>
            {t('Requires error logs')}
          </Badge>
        )
      }
      empty={props.points.length === 0}
      emptyMessage={t('No data available')}
      className='flex flex-col'
      contentClassName='flex flex-1 flex-col'
    >
      {/*
      注意：空数据分支由 PanelWrapper 处理。错误日志关闭时后端照样上报调用分桶，
      只是失败分桶恒为 0，因此「有桶」==「后端有返回」，只有真正无数据才会走空态。
      min-h-14 兜住单列（移动端）下卡片高度为 auto、h-full 无法求解时车道塌成 0 的情况。
      */}
      <div className='flex h-full min-h-14 items-end gap-px'>
        {props.points.map((point) => {
          const ratio = point.calls > 0 ? point.failures / point.calls : 0
          return (
            <span
              key={point.ts}
              className={cn(
                'min-w-px flex-1 rounded-t-sm',
                // 关闭错误日志时后端不上报失败分桶，此时按失败率着色会把所有桶画成
                // "健康"（绿色），属于会误导人的假象；改用中性色只表达调用量。
                props.errorLogEnabled
                  ? healthToneClass(ratio)
                  : 'bg-muted-foreground/40'
              )}
              // 车道铺满卡片高度、按该桶/最大桶归一，并留 2% 可见下限。
              // 0 调用的桶高度为 0（不画柱）但仍保留横向占位，否则时间轴会失真、
              // 空闲时段被视觉抹平：这里只改高度，不从数组里过滤。
              style={{
                height:
                  point.calls === 0
                    ? '0%'
                    : `${Math.max(2, (point.calls / maxCalls) * 100)}%`,
              }}
              title={
                props.errorLogEnabled
                  ? `${formatNumber(point.calls)} / ${formatNumber(point.failures)}`
                  : formatNumber(point.calls)
              }
            />
          )
        })}
      </div>
    </PanelWrapper>
  )
}

export function OverviewPage(props: OverviewPageProps) {
  const { t } = useTranslation()
  const range = resolveTimeRange(props.search, DEFAULT_SUMMARY_RANGE)
  const autoRefresh = props.search.autoRefresh ?? false

  const { data, isLoading } = useObservabilitySummary(range, {
    autoRefresh,
  })

  const summary = data?.summary
  const errorLogEnabled = data?.data_source.error_log_enabled ?? false
  const failureSource = data?.data_source.failure_source ?? 'none'
  const metrics = summary ? buildMetrics(summary, failureSource) : []
  const traffic = data?.traffic ?? []
  const hourly = data?.hourly_activity ?? []

  return (
    <SectionPageLayout stackActionsOnMobile>
      <SectionPageLayout.Title>{t('Dashboard')}</SectionPageLayout.Title>
      <SectionPageLayout.Actions>
        <RangeSelector
          range={range.range}
          start={range.start}
          end={range.end}
          onRangeChange={(nextRange, bounds) =>
            props.onSearchChange({
              range: nextRange,
              start: bounds?.start,
              end: bounds?.end,
              page: undefined,
            })
          }
        />
        <div className='flex items-center gap-2'>
          <Label
            htmlFor='observability-auto-refresh'
            className='text-muted-foreground text-xs font-normal'
          >
            {t('Auto Refresh (30s)')}
          </Label>
          <Switch
            id='observability-auto-refresh'
            size='sm'
            checked={autoRefresh}
            onCheckedChange={(checked) =>
              props.onSearchChange({ autoRefresh: checked || undefined })
            }
          />
        </div>
      </SectionPageLayout.Actions>
      <SectionPageLayout.Content>
        <div className='space-y-3 sm:space-y-4'>
          <PanelWrapper
            title={t('Real-time Traffic')}
            description={t('Last 60 seconds')}
            contentClassName='p-3 sm:p-5'
            headerActions={
              <div className='flex items-center gap-2'>
                <Badge variant='secondary' className='tabular-nums'>
                  {t('RPM')} {formatNumber(data?.rolling.rpm ?? 0)}
                </Badge>
                <Badge variant='secondary' className='tabular-nums'>
                  {t('TPM')} {formatCompactNumber(data?.rolling.tpm ?? 0)}
                </Badge>
              </div>
            }
          >
            {isLoading ? (
              <div className='grid grid-cols-2 gap-2 sm:grid-cols-3 sm:gap-3 lg:grid-cols-5'>
                {METRIC_KEYS.map((key) => (
                  <Skeleton key={key} className='h-24 rounded-xl' />
                ))}
              </div>
            ) : (
              <div className='grid grid-cols-2 gap-2 sm:grid-cols-3 sm:gap-3 lg:grid-cols-5'>
                {metrics.map((metric) => {
                  let description =
                    metric.description ??
                    (metric.descriptionKey ? t(metric.descriptionKey) : '')
                  if (metric.noteKey) {
                    description = description
                      ? `${description} · ${t(metric.noteKey)}`
                      : t(metric.noteKey)
                  }

                  return (
                    <StatCard
                      key={metric.key}
                      title={t(metric.titleKey)}
                      value={metric.value}
                      description={description}
                      icon={metric.icon}
                      tone={metric.tone}
                      compactMobile
                    />
                  )
                })}
              </div>
            )}
          </PanelWrapper>

          <div className='grid gap-3 sm:gap-4 lg:grid-cols-3'>
            <TopList
              title={t('Top Models')}
              rows={toTopModelRows(data?.top_models ?? [])}
              emptyMessage={t('No data available')}
            />
            <TopList
              title={t('Top API Keys')}
              rows={toTopTokenRows(data?.top_tokens ?? [])}
              emptyMessage={t('No data available')}
            />
            <TopList
              title={t('Top Channels')}
              rows={toTopChannelRows(data?.top_channels ?? [])}
              emptyMessage={t('No data available')}
            />
          </div>

          <ChartPanel
            title={t('Traffic Trend')}
            spec={buildTrafficTrendSpec(traffic, t)}
            loading={isLoading}
            empty={!isLoading && traffic.length === 0}
            emptyMessage={t('No data available')}
            height='h-72'
          />

          <div className='grid gap-3 sm:gap-4 lg:grid-cols-2'>
            <ChartPanel
              title={t('Hourly distribution (hour of day)')}
              spec={buildHourlyActivitySpec(hourly, t)}
              loading={isLoading}
              empty={!isLoading && hourly.length === 0}
              emptyMessage={t('No data available')}
              height='h-64'
            />
            <HealthTimelinePanel
              points={data?.health_timeline ?? []}
              errorLogEnabled={errorLogEnabled}
              loading={isLoading}
            />
          </div>

          {!isLoading && data && (
            <div className='text-muted-foreground flex flex-wrap items-center gap-x-4 gap-y-1 text-xs'>
              <span className='inline-flex items-center gap-1.5'>
                <Coins className='size-3.5' aria-hidden='true' />
                {t('{{count}} log rows scanned', {
                  count: data.data_source.log_rows,
                })}
              </span>
            </div>
          )}
        </div>
      </SectionPageLayout.Content>
    </SectionPageLayout>
  )
}

const METRIC_KEYS = [
  'calls',
  'tokens',
  'cost',
  'latency',
  'success',
  'prompt-tokens',
  'completion-tokens',
  'cached-tokens',
  'stream-calls',
  'active-keys',
] as const
